{
    "name": "Deploy",
    "on": {
        "push": {
            "branches": ["prod"],
        },
    },
    "jobs": {
        "deploy": {
            "runs-on": "ubuntu-latest",
            "steps": [
                {
                    "uses": "actions/checkout@v3",
                    "with": {
                        "submodules": true,
                    },
                },
                {
                    "name": "Install Rust",
                    "uses": "actions-rs/toolchain@v1",
                    "with": {
                        "profile": "minimal",
                        "toolchain": "stable",
                        "override": true,
                    },
                },
                {
                    "name": "Cache Rust",
                    "uses": "Swatinem/rust-cache@v1",
                    "with": { "working-directory": "builder" },
                },
                {
                    "name": "Install npm",
                    "uses": "actions/setup-node@v2",
                    "with": {
                        "node-version": "16",
                        "cache": "npm",
                        "cache-dependency-path": "builder/js/package-lock.json",
                    },
                },
                {
                    "name": "Build",
                    "run": "./build",
                },
                {
                    "name": "Deploy",
                    "uses": "JamesIves/github-pages-deploy-action@v4.2.5",
                    "with": {
                        "branch": "gh-pages",
                        "folder": "dist"
                    },
                },
            ],
        },
    },
}
